baseURL = 'https://sinapradip.github.io/tibetdiariesfork/'
languageCode = 'en-us'
title = 'Tibet Diaries'
theme = 'PaperMod'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
email = "tibetdiaries@gmail.com"

relativeURLs = true
canonifyURLs = true