baseURL = 'https://github.com/sinapradip/tibetdiariesfork'
languageCode = 'en-us'
title = 'Tibet Diaries'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
email = "tibetdiaries@gmail.com"